-- Migration 009: Presence / Live Ping
-- presence_pings  (persistent live ping records for accountability + admin history)
-- Source: drizzle/0013_presence_pings.sql, docs/migrations/add-presence-pings.sql

-- Depends on: 20260617000001_core_hr.sql (users)

-- ─────────────────────────────────────────────────────────────────────────────
-- presence_pings
-- ─────────────────────────────────────────────────────────────────────────────
-- Admin sends a ping to a team member to confirm they are online.
-- Member has until deadline_at to acknowledge. Missing the deadline
-- records missed_at and flips status to 'missed'.
CREATE TABLE IF NOT EXISTS presence_pings (
  id               TEXT PRIMARY KEY,       -- nanoid / uuid generated by app
  from_user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  from_name        TEXT NOT NULL,          -- snapshot at send time
  from_role        TEXT NOT NULL,
  from_team        TEXT,
  from_photo_url   TEXT,
  to_user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message          TEXT NOT NULL,
  response_message TEXT,
  status           TEXT NOT NULL DEFAULT 'pending',  -- pending | acknowledged | missed
  created_at       TIMESTAMPTZ NOT NULL,
  deadline_at      TIMESTAMPTZ NOT NULL,
  acknowledged_at  TIMESTAMPTZ,
  missed_at        TIMESTAMPTZ,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT presence_pings_status_chk CHECK (status IN ('pending', 'acknowledged', 'missed'))
);

CREATE INDEX IF NOT EXISTS presence_pings_from_created_idx
  ON presence_pings(from_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS presence_pings_to_created_idx
  ON presence_pings(to_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS presence_pings_status_deadline_idx
  ON presence_pings(status, deadline_at);
